### ISSUE TITLE
Liens inversés pour Adib / Alex Forest

### ISSUE THREAD

**Issue by h3xstream** [maxmx/mobilo#2]
Sur la page d'accueil: https://www.drmobilo.com/
Dans les spectacles du 8 mai, **les liens vers les spectacles** d'Alex Forest et Adib sont inversés.
Les autres dates semblent ok..

**Comment by maxmx** [comment]
Étrange, tu utilise quel appareil pour visiter le site? J’ai le behavior correct sur mon laptop et mon iPhone.

J’imagine que tu parles du 7 mai, mais j’ai aussi essayé le 6 mai.

**Comment by h3xstream** [comment]
Navigateur Chrome

![mobilo2](https://user-images.githubusercontent.com/593130/55890493-c1fc7500-5b80-11e9-9f20-b7476aef0917.gif)

**Comment by h3xstream** [comment]
Même comportement sur Firefox.

**Comment by h3xstream** [comment]
Les événements inversés sont ceux dont les dates (date et heure) sont les même.

Je n'ai pas débuggé mais il pourrait s'agir d'une collision comme l'utilisation d'une map avec comme clé unique la date.

https://github.com/maxmx/mobilo/blob/0a3dca19b1d1ab6bba6857b6c7e7b80d53b321fa/src/components/Home/index.js#L20-L27

**Comment by mbergeronupgrade** [comment]
Clairement, je vois le problème maintenant, je comprenais pas puisque quand je click ça se rends quand même à la même page. Merci pour le hint!

**Comment by maxmx** [comment]
Je croyais que c'était les keys, mais finalement elles sont toutes uniques. J'ai découvert que le problème se produit seulement quand le build est fait sur les serveur de zeit now.

Ici déployé un build de ma machine qui ne montre pas le bug.

https://public.maxmx.now.sh/


Merci pour le bug, je vais investiguer d'avantage.

**Comment by maxmx** [comment]
Allright, c'était le time zone. Le builder est pas dans le même timezone, donc le output static du site à ni les bonnes journées, ni les bonnes heures, et quand le js embarque sur la page le contenu n'est plus dans le même ordre. On peut voir le flash du changement de contenu quand ça arrive, mais les liens restent erronés.

JS Disabled:

![image](https://user-images.githubusercontent.com/2332621/55903448-a9e61f00-5b9b-11e9-8652-43a66b07997d.png)


JS Enabled, apres le flash de contenu.
![image](https://user-images.githubusercontent.com/2332621/55903486-c1bda300-5b9b-11e9-86ed-bb4291c7f0ab.png)
